//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
	public partial class GameMainPanel : UIWindow
	{
		#region 脚本工具生成的代码

		private UIBindComponent m_bindComponent;
		private Slider m_sliderHP = null!;
		private TextMeshProUGUI m_tmpName = null!;
		private Image m_imgHead = null!;

		protected override void ScriptGenerator()
		{
			m_bindComponent = gameObject.GetComponent<UIBindComponent>();
			if(m_bindComponent == null)
			{
				Log.Error($"根物体: {gameObject.name} 缺少组件 UIBindComponent, 请检查！！！");
				return;
			}
			m_sliderHP = m_bindComponent.GetComponent<Slider>(0);
			m_tmpName = m_bindComponent.GetComponent<TextMeshProUGUI>(1);
			m_imgHead = m_bindComponent.GetComponent<Image>(2);
			m_sliderHP.onValueChanged.RemoveAllListeners();
			m_sliderHP.onValueChanged.AddListener(OnSliderHPChange);
		}

		#endregion

		#region 事件

		private partial void OnSliderHPChange(float value);

		#endregion
	}
}
