//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
	public partial class LoadingPanel : UIWindow
	{
		#region 脚本工具生成的代码

		private UIBindComponent m_bindComponent;
		private Slider m_sliderProgress = null!;
		private TextMeshProUGUI m_tmpLoadingContent = null!;
		private TextMeshProUGUI m_tmpContent1 = null!;
		private TextMeshProUGUI m_tmpContent2 = null!;

		protected override void ScriptGenerator()
		{
			m_bindComponent = gameObject.GetComponent<UIBindComponent>();
			if(m_bindComponent == null)
			{
				Log.Error($"根物体: {gameObject.name} 缺少组件 UIBindComponent, 请检查！！！");
				return;
			}
			m_sliderProgress = m_bindComponent.GetComponent<Slider>(0);
			m_tmpLoadingContent = m_bindComponent.GetComponent<TextMeshProUGUI>(1);
			m_tmpContent1 = m_bindComponent.GetComponent<TextMeshProUGUI>(2);
			m_tmpContent2 = m_bindComponent.GetComponent<TextMeshProUGUI>(3);
			m_sliderProgress.onValueChanged.RemoveAllListeners();
			m_sliderProgress.onValueChanged.AddListener(OnSliderProgressChange);
		}

		#endregion

		#region 事件

		private partial void OnSliderProgressChange(float value);

		#endregion
	}
}
