//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using TMPro;
using Cysharp.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
	public partial class LoginPanel : UIWindow
	{
		#region 脚本工具生成的代码

		private UIBindComponent m_bindComponent;
		private InputField m_inputAccount = null!;
		private InputField m_inputPassword = null!;
		private Button m_btnLogin = null!;
		private Button m_btnSayHi = null!;
		private Button m_btnConnect = null!;
		private Text m_textNetStatus = null!;
		private Button m_btnRegion = null!;
		private TextMeshProUGUI m_tmpRegion = null!;

		protected override void ScriptGenerator()
		{
			m_bindComponent = gameObject.GetComponent<UIBindComponent>();
			if(m_bindComponent == null)
			{
				Log.Error($"根物体: {gameObject.name} 缺少组件 UIBindComponent, 请检查！！！");
				return;
			}
			m_inputAccount = m_bindComponent.GetComponent<InputField>(0);
			m_inputPassword = m_bindComponent.GetComponent<InputField>(1);
			m_btnLogin = m_bindComponent.GetComponent<Button>(2);
			m_btnSayHi = m_bindComponent.GetComponent<Button>(3);
			m_btnConnect = m_bindComponent.GetComponent<Button>(4);
			m_textNetStatus = m_bindComponent.GetComponent<Text>(5);
			m_btnRegion = m_bindComponent.GetComponent<Button>(6);
			m_tmpRegion = m_bindComponent.GetComponent<TextMeshProUGUI>(7);
			m_btnLogin.onClick.RemoveAllListeners();
			m_btnLogin.onClick.AddListener(UniTask.UnityAction(OnClickLoginBtn));
			m_btnSayHi.onClick.RemoveAllListeners();
			m_btnSayHi.onClick.AddListener(OnClickSayHiBtn);
			m_btnConnect.onClick.RemoveAllListeners();
			m_btnConnect.onClick.AddListener(OnClickConnectBtn);
			m_btnRegion.onClick.RemoveAllListeners();
			m_btnRegion.onClick.AddListener(OnClickRegionBtn);
		}

		#endregion

		#region 事件

		private partial UniTaskVoid OnClickLoginBtn();

		private partial void OnClickSayHiBtn();

		private partial void OnClickConnectBtn();

		private partial void OnClickRegionBtn();

		#endregion
	}
}
