
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial struct vector2int
{
    public vector2int(ByteBuf _buf) 
    {
        x = _buf.ReadInt();
        y = _buf.ReadInt();
    }

    public static vector2int Deserializevector2int(ByteBuf _buf)
    {
        return new vector2int(_buf);
    }

    public readonly int x;
    public readonly int y;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "x:" + x + ","
        + "y:" + y + ","
        + "}";
    }
}
}

