
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class LocConfig : Luban.BeanBase
{
    public LocConfig(ByteBuf _buf) 
    {
        ID = _buf.ReadString();
        {int __n0 = _buf.ReadSize(); Content = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); Content[__index0] = __e0;}}
    }

    public static LocConfig DeserializeLocConfig(ByteBuf _buf)
    {
        return new LocConfig(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// en
    /// </summary>
    public readonly string[] Content;
   
    public const int __ID__ = -56573310;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Content:" + Luban.StringUtil.CollectionToString(Content) + ","
        + "}";
    }
}
}

