
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public TbLocConfig TbLocConfig {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbLocConfig = new TbLocConfig(loader("tblocconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbLocConfig.ResolveRef(this);
    }
}

}
