
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbLocConfig
{
    private readonly System.Collections.Generic.Dictionary<string, LocConfig> _dataMap;
    private readonly System.Collections.Generic.List<LocConfig> _dataList;
    
    public TbLocConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, LocConfig>(n);
        _dataList = new System.Collections.Generic.List<LocConfig>(n);
        for(int i = n ; i > 0 ; --i)
        {
            LocConfig _v;
            _v = global::GameConfig.LocConfig.DeserializeLocConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, LocConfig> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<LocConfig> DataList => _dataList;

    public LocConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LocConfig Get(string key) => _dataMap[key];
    public LocConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

