
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial struct vector4
{
    public vector4(ByteBuf _buf) 
    {
        x = _buf.ReadFloat();
        y = _buf.ReadFloat();
        z = _buf.ReadFloat();
        w = _buf.ReadFloat();
    }

    public static vector4 Deserializevector4(ByteBuf _buf)
    {
        return new vector4(_buf);
    }

    public readonly float x;
    public readonly float y;
    public readonly float z;
    public readonly float w;
   

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "x:" + x + ","
        + "y:" + y + ","
        + "z:" + z + ","
        + "w:" + w + ","
        + "}";
    }
}
}

